/**
 * Public surface for the Neeme HTTP API client.
 *
 * Callers import from here (`@shared/api`), never from `./generated/*` — that
 * folder is regenerated by `pnpm gen:api` and its names track FastAPI's verbose
 * operationIds (e.g. `healthHealthGet`). Re-exporting here gives stable, ergonomic
 * names and one place to adjust if the generator output shifts.
 *
 * Importing `./generated/client.gen` also initializes the shared client with our
 * runtime config (base URL + auth seam from `./runtime.ts`).
 */
import { healthHealthGet } from './generated'

/** GET /health — backend configuration status. Needs no params or auth. */
export const getHealth = healthHealthGet

// Re-export response/data types for callers that want them.
export type { HealthHealthGetResponses } from './generated'
