/**
 * Public surface for the Neeme HTTP API client.
 *
 * Callers import from here (`@shared/api`), never from `./generated/*` — that
 * folder is regenerated by `pnpm gen:api` and its names track FastAPI's verbose
 * operationIds (e.g. `healthHealthGet`). Re-exporting here gives stable, ergonomic
 * names and one place to adjust if the generator output shifts.
 *
 * Importing the generated SDK also initializes the shared client with our runtime
 * config (base URL + auth seam from `./runtime.ts`).
 *
 * NOTE on type-safety: request inputs ARE typed (NoteIn, TodoIn, query params),
 * but responses are currently `unknown` — the FastAPI handlers return plain dicts
 * with no `response_model`, so the OpenAPI spec declares no response schema. The
 * high-leverage next step for a fully-typed stack is adding response models on the
 * backend, after which `pnpm gen:api` yields typed responses here for free.
 */
import {
  healthHealthGet,
  ingestIngestPost,
  addNoteNotesPost,
  searchSearchGet,
  recentRecentGet,
  getItemItemsItemIdGet,
  forgetItemsItemIdDelete,
  todayTodayGet,
  addTodoTodosPost,
  patchTodoTodosTodoIdPatch,
  deleteTodoTodosTodoIdDelete,
  todoContextTodosTodoIdContextGet
} from './generated'

/**
 * Unwrap a hey-api result (`{ data, error, response }`) into `data`, throwing a
 * readable Error on failure. Lets components `await unwrap(getRecent(...))` and
 * work with the typed payload directly. Network failures (server down) surface
 * as the rejected promise from the underlying fetch.
 */
export async function unwrap<T>(
  call: Promise<{ data?: T; error?: unknown; response?: Response }>
): Promise<T> {
  const { data, error, response } = await call
  if (error !== undefined || data === undefined) {
    throw new Error(`Request failed (HTTP ${response?.status ?? '?'})`)
  }
  return data
}

// ---- Memory / item capture + retrieval ----
/** GET /health — backend configuration status. No params, no auth. */
export const getHealth = healthHealthGet
/** POST /ingest — multipart file upload (file + optional tags). */
export const ingest = ingestIngestPost
/** POST /notes — quick text capture. */
export const addNote = addNoteNotesPost
/** GET /search — semantic search (q, top_k, type). */
export const search = searchSearchGet
/** GET /recent — recently captured items. */
export const getRecent = recentRecentGet
/** GET /items/{id} — full record (+ presigned raw_url). */
export const getItem = getItemItemsItemIdGet
/** DELETE /items/{id} — forget an item (S3 + Redis + Search). */
export const forgetItem = forgetItemsItemIdDelete

// ---- Daily to-do list (the retrieval anchor) ----
/** GET /today — the day's to-do list. */
export const getToday = todayTodayGet
/** POST /todos — add a to-do; returns it plus surfaced memory context. */
export const addTodo = addTodoTodosPost
/** PATCH /todos/{id} — edit / complete / reorder. */
export const patchTodo = patchTodoTodosTodoIdPatch
/** DELETE /todos/{id} — remove a to-do. */
export const deleteTodo = deleteTodoTodosTodoIdDelete
/** GET /todos/{id}/context — memories relevant to a to-do. */
export const getTodoContext = todoContextTodosTodoIdContextGet

// ---- Request input types ----
export type { NoteIn, TodoIn, TodoPatch, BodyIngestIngestPost } from './generated'

// ---- Response types (now typed from the backend's Pydantic response_models) ----
export type {
  ItemSummary,
  IngestResponse,
  RecentResponse,
  SearchHitView,
  SearchResponse,
  HealthHealthGetResponses
} from './generated'
