name: Changelog

on:
  workflow_dispatch:

# on:
#   push:
#     branches:
#       - main

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          # GITHUB_REPO: ${{ github.repository }}

      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"

      # use release body in the same job
      # - name: Upload the binary releases
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     file: binary_release.zip
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     tag: ${{ github.ref }}
      #     body: ${{ steps.git-cliff.outputs.content }}

  # use release body in another job
  # upload:
  #   name: Upload the release
  #   needs: changelog
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Upload the binary releases
  #       uses: svenstaro/upload-release-action@v2
  #       with:
  #         file: binary_release.zip
  #         repo_token: ${{ secrets.GITHUB_TOKEN }}
  #         tag: ${{ github.ref }}
  #         body: ${{ needs.changelog.outputs.release_body }}
